### PR TITLE
make build Scala 2.13 friendly

### PR DESCRIPTION
**Pull request by SethTisue**
scala-parallel-collections is a module now

### CODE REVIEW

**Comment by SethTisue** [comment]
these changes are necessary in order to keep specs2 in the Scala 2.13 community build

**Comment by etorreborre** [comment]
Thanks @SethTisue. I don't even remember where and why I'm using parallel collections :-).

**Comment by SethTisue** [comment]
the single usage is in https://github.com/etorreborre/specs2/blob/master/tests/src/test/scala/org/specs2/matcher/TraversableMatchersSpec.scala

**Comment by etorreborre** [comment]
Right, I suspect I must have had a bug with that at some point.

**Pull request merged**
