### PR TITLE
update to Scala 2.13.0

### PR DESCRIPTION
**Pull request by kailuowang**

### CODE REVIEW

**Comment by symbiont-eric-torreborre** [comment]
Thanks, I started looking at publishing, I'm just waiting on cats now, do you know when it will be ready?

**Comment by kailuowang** [comment]
Thanks @symbiont-eric-torreborre I am working on cats. I need a specs2 release on 2.13 to unblock discipline, which blocks Cats. Unfortunately there is a circular dependency cats -> discipline -> specs2
 -> cats

**Comment by etorreborre** [comment]
Oh, I didn't realize that. How do you break the cycle then? You publish specs2 locally, then discipline and cats for everyone? Maybe I should extract `specs2-cats` somewhere to avoid this

**Comment by kailuowang** [comment]
TBC, It's just circular build dependency,  Cats does not depend on specs 2 jars.

**Comment by kailuowang** [comment]
As we've done in the past, we publish specs2 4.5.1 2.13.0 , but it depends on Cats 1.6.0_2.13.0_M5, later, once Cats 2.0.0-RC1_2.13 is released we can update specs 2.

**Comment by kailuowang** [comment]
I can publish specs2 locally as well, but then it won't pass the build for a discipline PR.

**Comment by etorreborre** [comment]
Ok, so today you suggest that I publish specs2 with cats on `2.13.0-RC3`. I can do that

**Comment by kailuowang** [comment]
@etorreborre yeah, thanks I think it's either cats-2.13.0-M5_1.6.0 or Cats_2.13.0-RC3_2.0.0-M3, I don't think we have cats 1.6.0 on Scala2.13.0-RC3

**Comment by etorreborre** [comment]
It is published now

**Comment by kailuowang** [comment]
Thanks very much!

**Pull request merged**
