### PR TITLE
Fix fatal error issues (#822)

### PR DESCRIPTION
**Pull request by ivan-klass**
Not sure if it's a correct way to fix the issue, but I think that should help

### CODE REVIEW

**Comment by etorreborre** [comment]
Yes I think it makes sense, thanks!

**Comment by ivan-klass** [comment]
@etorreborre the failing CI point me to the spec that no fatal errors should be caught 
https://github.com/etorreborre/specs2/blob/2cfada84c67bc897919b31bf6e64b481ab11324b/core/jvm/src/test/scala/org/specs2/execute/ResultExecutionSpec.scala#L38-L39
The related commit message emphasize on catching **non-fatal**: https://github.com/etorreborre/specs2/commit/d568a9307c994a3f976b3905c08bc6b08be81ccf

I'm totally ok with that as soon as test runner will also throw the fatal error, not run forever. I still can't figure out why the execution stuck in a loop, could you please help?

**Comment by etorreborre** [comment]
I'll investigate and come back to you soon.

**Comment by ivan-klass** [comment]
Closed as out-dated, original #822 task is resolved

**Pull request closed without merging**
