### PR TITLE
Upgrade to JUnit 5 (vintage)

### LINKED ISSUE #713: JUnit 5?
Hello,

is it possible to upgrade to latest JUnit 5.3.1?
https://github.com/etorreborre/specs2/blob/9f93c270421a27bec8001d363f69ca02b5c6fa4f/project/depends.scala#L42

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #713

Using JUnit 5 Vintage allows us to run vintage JUnit tests (tests written in the JUnit 4 style) on the new JUnit Platform. Therefore we don't need to upgrade the tests itself yet.

See https://www.baeldung.com/junit-5-migration:
> JUnit Vintage aids in the migration of JUnit tests by running JUnit 3 or JUnit 4 tests within the JUnit 5 context.

Also https://junit.org/junit5/docs/current/user-guide/#dependency-metadata-junit-vintage
> JUnit Vintage test engine implementation that allows to run vintage JUnit tests, i.e. tests written in the JUnit 3 or JUnit 4 style, on the new JUnit Platform.

JUnit 5 releases: https://github.com/junit-team/junit5/releases

Why upgrade?
So frameworks that use specs2 can also upgrade to JUnit 5 without conflicting dependencies.

### CODE REVIEW

**Comment by mkurz** [comment]
Actually I am not sure if this is correct...

**Comment by etorreborre** [comment]
@mkurz what would be incorrect? Did you try it on different versions of your own code with JUnit specs?

**Comment by etorreborre** [comment]
`master` is now on `junit-vintage-engine-5.3.2`

**Comment by mkurz** [comment]
@etorreborre Great! Sorry I didn't continue to work on this, I was busy with lots of other things.
I just checked, junit(-vintage) 5.7.2 is the latest version, probably it would make sense to use that latest version (?) https://github.com/junit-team/junit5/releases/

**Comment by etorreborre** [comment]
I was only following the `scala-steward` updates :-). I'll update to the latest. That being said, despite the version bump [it seems that more work is still necessary anyway](https://github.com/etorreborre/specs2/issues/713#issuecomment-607389866).

**Pull request closed without merging**
