### PR TITLE
update sbt plugin version

### PR DESCRIPTION
**Pull request by magnolia-k**
When starting sbt, the following warning is issued, so updated the version of sbt plugins.

[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 
[warn] 	* com.typesafe.sbt:sbt-git:0.8.0 is selected over 0.6.1
[warn] 	    +- default:specs2-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13) (depends on 0.8.0)
[warn] 	    +- com.typesafe.sbt:sbt-ghpages:0.5.1 (scalaVersion=2.10, sbtVersion=0.13) (depends on 0.6.1)
[warn] 
[warn] Run 'evicted' to see detailed eviction warnings

### CODE REVIEW

**Comment by etorreborre** [comment]
Thanks, the travis build is failing with 
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
[info] Loading project definition from /home/travis/build/etorreborre/specs2/project
java.lang.NoSuchMethodError: sbt.package$.Zero()Lsbt/Global$;
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$scalaJSStageSettings(ScalaJSPluginInternal.scala:254)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$22.apply(ScalaJSPluginInternal.scala:446)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$22.apply(ScalaJSPluginInternal.scala:446)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:54)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:130)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
```
Do you have any idea why?

**Comment by xuwei-k** [comment]
https://www.scala-js.org/news/2017/09/01/announcing-scalajs-0.6.20/

> sbt 0.13.16 or above is required 
> The sbt plugin of Scala.js 0.6.20 starts using features of sbt 0.13.16. If you are using an older version of sbt 0.13.x, you will have to upgrade to 0.13.16 or later.

https://github.com/etorreborre/specs2/blob/45117b7ca23320b0663630f9d010ce3a9fbbe959/.travis-test.sh

**Comment by etorreborre** [comment]
Thanks @xuwei-k. @magnolia-k can you please update the `.travis.yaml` file in your PR?

**Comment by etorreborre** [comment]
All good now, thanks again @magnolia-k and @xuwei-k

**Pull request merged**
