### PR TITLE
Allow matching special line characters with regex #764

### PR DESCRIPTION
**Pull request by mantasak**
This fixes the issue referred to in #764.

### CODE REVIEW

**Comment by etorreborre** [comment]
Thanks a lot for this! I have a concern though. Some tests are now failing with
```
[error] x typecheck("val a: String = 1") must failWith("type mismatch")
[error]  type mismatch;
[error]   found   : Int(1)
[error]   required: String
[error]   doesn't match
[error]  type mismatch (TypecheckMatcherSpec.scala:14)
```
The reason is that `failWith(r)` expects a regular expression for `r` which will not care about newlines. So I would propose that you change the `failWith` matcher to suppress newlines there instead of doing it in `matchesSafely`.

**Comment by mantasak** [comment]
I agree with you, will look into it. Couldn't get the entire repo to build locally successfully, so unfortunately did not notice the failing tests.

**Comment by mantasak** [comment]
@symbiont-eric-torreborre I made the changes.

Please let me know if I understood your suggestion correctly.

**Comment by etorreborre** [comment]
Yes all good thanks!

**Pull request merged**
