### PR TITLE
[WIP] Adding support for sbt-crossproject

### PR DESCRIPTION
**Pull request by mdedetrich**
This PR is designed to add support for sbt-crossproject. Its also designed to clean up the build a little bit. After sbt-crossproject support is merged its fairly trivial to add support for scala-native

### CODE REVIEW

**Comment by etorreborre** [comment]
Great I was not aware of that plugin.

**Comment by francisdb** [comment]
@mdedetrich did you actually try a js/native build?

**Comment by mdedetrich** [comment]
@francisdb What do you mean?

**Comment by mdedetrich** [comment]
@francisdb What do you mean?

**Comment by francisdb** [comment]
> After sbt-crossproject support is merged its fairly trivial to add support for scala-native
I was wondering if you tried that after the merge

**Comment by mdedetrich** [comment]
I can't remember, I did it so long ago. Is it currently breaking something?

**Comment by francisdb** [comment]
Not that I know, just wanted to know if somebody attempted adding support for scala native

**Comment by mdedetrich** [comment]
Ah right, I think there were some blockers for native (such as scalacheck) but I didn't specifically tryit (although this was a first step)

**Pull request merged**
