### PR TITLE
reduce duplication

### PR DESCRIPTION
**Pull request by noam-almog**
Glad to see you further integrated the diffable to actually check the result in the EqualityMatcher.
While looking at this code, I want to suggest a different approach, tell me what you think ?

 - Noam

### CODE REVIEW

**Comment by etorreborre** [comment]
I think that's a good idea but sealing the traits mean that they cannot be reused outside of specs2.

**Comment by noam-almog** [comment]
@etorreborre removing sealed

**Comment by etorreborre** [comment]
Can you please squash the 2 commits into one with a message like `reduce duplication for comparison results`? Thanks.

**Comment by noam-almog** [comment]
👍

**Pull request merged**
